### ISSUE TITLE
Feature: audio formats

### ISSUE THREAD

**Issue by dromer** [corkami/pics#13]
While there are several image and video formats in the binary section, it would be great to have some common audio formats in there as well :)

**Comment by angea** [comment]
Actually...
https://speakerdeck.com/ange/technical-challenges-with-file-formats

Note that the video formats are very recent ;)

**Comment by dromer** [comment]
While a nice presentation, I'm not sure how this completes the request ;)

**Comment by angea** [comment]
MP3 ;)

**Comment by dromer** [comment]
There's more than just MP3 of course. WAV, FLAC, OGG, AIFF, etc.

Also this is now hidden inside several slides in a presentation not in the nice format you have here in the repo.
It would be nice to have them as single images like the other binary formats.

**Comment by angea** [comment]
In the meantime...
https://github.com/corkami/pics/blob/master/binary/WAV.png
![image](https://user-images.githubusercontent.com/5624411/209813739-a9134aac-a63a-44b4-ab34-cf6a4cbf0536.png)

**Comment by dromer** [comment]
Oooooh, why did I miss this one -_-

Thnx :)

**Comment by angea** [comment]
And its bigger brother...
![image](https://user-images.githubusercontent.com/5624411/209815191-24581645-23dc-4b61-a6fe-eed04db460b3.png)

**Comment by pablodz** [comment]
i was looking for wav, thx
