### ISSUE TITLE
About exif metadata

### ISSUE THREAD

**Issue by guvenacar** [corkami/pics#16]
I want to read and write metadata information of Jpeg files in byte or binary format. How can I find where the exif information starts and ends when I open a jpeg file in byte format? Does the Start Of Scan section in the diagram below mean that image pixels (RGB) are located in this area? I think this diagram represents a jpeg model without exif. If it contained exif information, where would it appear in the diagram below? Thanks.

![resim_2023-12-11_234715002](https://github.com/corkami/pics/assets/78052322/51902f32-4e8f-4ff7-9500-960fada4e700)

**Comment by angea** [comment]
an App0 secgment, followed by an App1 segment containing Exif in an TIFF-like IFD...
<img width="710" alt="image" src="https://github.com/corkami/pics/assets/5624411/c121adbf-bfaf-4473-b2bd-5859ec3837e9">

**Comment by guvenacar** [comment]
Thanks angea.
