### ISSUE TITLE
JPEG poster labeling

### ISSUE THREAD

**Issue by kyle-rb** [corkami/pics#7]
In the JPEG poster, the second Huffman table's class is listed as "0 (DC)", when I think it should be "1 (AC)". The value in the hex data that this label refers to is correct (1), so the label just needs to reflect it.

**Comment by l4ckyguy** [comment]
please mail me
tebya[ . ]poime.li or l4ckyguy[ . ]gmail.com
or send message to tg @x4kme or @l4ckyguy
it is very important

**Comment by x-N0** [comment]
Been this fixd?

**Comment by sdatko** [comment]
> Been this fixd?

Not yet: https://github.com/corkami/pics/blob/master/binary/JPG.png

I marked the bad values with blue lines here:
![maim-2022-04-13-12-49-15-CEST-1649846955-13864-lines](https://user-images.githubusercontent.com/29290344/163165476-9c307186-1b73-4fd9-9795-ccd844786138.png)

Indeed it should be DC AC DC AC
